config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    devise_for :users, skip: :invitations, controllers: {registrations: "users/registrations", sessions: "users/sessions"}

    devise_scope :user do
      # Just the wanted subset of invitable routes
      get "/users/invitation/accept" => "devise/invitations#edit", :as => :accept_user_invitation
      put "/users/invitation" => "devise/invitations#update", :as => :user_invitation
    end

    unauthenticated do
      root "pages#presentation"
    end

    authenticated :user do
      root "maps#index", as: :user_root
    end

    resources :maps do
      resources :layers, only: [:new]
      resources :user_roles, only: [:index, :create, :update, :destroy], shallow: true
      resources :map_tokens, only: [:index, :create, :update, :destroy], shallow: true
      namespace :import do
        resources :operations, only: [:index, :new, :create, :show, :update, :destroy], shallow: true, namespace: :import
      end
    end
    resources :layers, except: [:index, :new] do
      resources :fields, only: [:new, :create, :edit, :update, :destroy], shallow: true
      resources :rows, only: [:new, :create, :show, :edit, :update, :destroy], shallow: true
      member do
        get "/mvt/:z/:x/:y/", action: :mvt
      end
    end

    resources :territory_categories, only: [:index, :show]
    resources :territories, only: [:show] do
      collection do
        get "search"
      end
    end

    get "/legal" => "pages#legal"
    get "/legal/conditions" => "pages#legal_conditions"
    get "/legal/data" => "pages#legal_data"
    get "/presentation" => "pages#presentation"
    get "/crowdsourcing" => "pages#use_case_crowdsourcing"
    get "share/:token", to: "maps#shared", as: "map_shared"
    get "layers/:id/geojson", to: redirect("layers/%{id}.geojson")
    get ".well-known/change-password", to: redirect("/users/edit")

    # URLs specific to the instance on cocarto.com
    get "/s/infolettre", to: redirect("https://buttondown.email/cocarto")
    get "/s/geodatadays", to: redirect("https://cocarto.com/share/dg4V524mFETB5Zoo")
    get "/s/commune_de_paris", to: redirect("https://cocarto.com/share/kxw8CL5tD42Do26z"), as: "share_commune_de_paris"
    get "/s/manifs_retraites", to: redirect("https://cocarto.com/share/xuzDBpYpv7jyH_aC"), as: "share_manifs_retraites"
    get "/s/gr20", to: redirect("https://cocarto.com/fr/share/f7iw5cSrm3sdCKRb"), as: "share_gr20"
    get "/s/ymca", to: redirect("https://cocarto.com/fr/share/TQxqzWYz9VYVBpgy")
    get "/s/ymca_m", to: redirect("https://cocarto.com/fr/layers/b00b15eb-c525-40ec-9e2a-1ea0ebf9330e/rows/new?token=TQxqzWYz9VYVBpgy")

    namespace :admin do
      resources :users, only: [:index, :destroy]
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  if Rails.env.development?
    mount GoodJob::Engine, at: "good_job"
    mount ActiveAnalytics::Engine, at: "analytics"
  else
    authenticate :user, ->(user) { user.admin? } do
      mount GoodJob::Engine, at: "good_job"
      mount ActiveAnalytics::Engine, at: "analytics"
    end
  end
end

app/models/map.rb
# == Schema Information
#
# Table name: maps
#
#  id                :uuid             not null, primary key
#  base_style_url    :text
#  default_latitude  :float
#  default_longitude :float
#  default_zoom      :float
#  name              :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Map < ApplicationRecord
  include Mvt::MapStyle

  # Relations
  has_many :user_roles, dependent: :destroy, inverse_of: :map
  has_many :map_tokens, dependent: :destroy, inverse_of: :map
  has_many :layers, dependent: :destroy
  has_many :import_configurations, class_name: "Import::Configuration", dependent: :destroy

  # Through relations
  has_many :import_operations, class_name: "Import::Operation", through: :import_configurations, source: "operations"

  accepts_nested_attributes_for :layers

  # Through relations
  has_many :users, through: :user_roles, inverse_of: :maps
  has_many :rows, through: :layers, inverse_of: :map

  # Query as scopes
  scope :with_last_updated_row_id, -> do
    left_outer_joins(:rows)
      .order("maps.id, rows.updated_at DESC NULLS LAST")
      .select("DISTINCT ON (maps.id) maps.*, rows.id as computed_last_updated_row_id")
  end
  belongs_to :last_updated_row, class_name: "Row", optional: true, foreign_key: "computed_last_updated_row_id" # rubocop:disable Rails/InverseOf

  # Hooks
  after_update_commit do
    if name_previously_changed?
      broadcast_i18n_replace_to self, target: dom_id(self, :name), partial: "maps/name"
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_base_map_styles
  before_action :new_map, only: %i[new create]
  before_action :set_map, only: %i[show edit update destroy]

  def index
    @maps = policy_scope(Map).includes(:layers, :user_roles)
    @maps_rows_count = policy_scope(Map).joins(:rows).group("maps.id").count("rows.id")
    @maps_rows_count.default = 0

    @new_map = Map.new
    @new_map.user_roles.new(user: current_user, role_type: :owner)
  end

  def show
    @role_type = current_user.access_for_map(@map).role_type
    @initially_active_layer = @map.layers.find_by(id: params["open"])

    respond_show
  end

  def shared
    # Access made with a map token.
    # Authentication is already done by MapTokenAuthenticatable.
    map_token = MapToken.find_by(token: params[:token])
    current_user.assign_map_token(map_token)
    if current_user.anonymous?
      # Transient users only see the /share/:token url
      @map = authorize(map_token.map)
      @role_type = map_token.role_type

      respond_show
    else
      # Real users are redirected to /maps/:id
      redirect_to authorize(map_token.map)
    end
  end

  def new
    @map.layers.new
    render "form"
  end

  def edit
    render "form"
  end

  def create
    if @map.update(map_params)
      redirect_to map_path(@map)
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render "new", status: :unprocessable_entity
    end
  end

  def update
    if @map.update(map_params)
      if [:default_latitude, :default_longitude, :default_zoom].any? { _1.in? @map.previous_changes }
        flash.now[:notice] = t("helpers.message.map.center_and_zoom_saved")
      end
      respond_to do |format|
        format.turbo_stream { render turbo_stream: [] }
        format.html { redirect_to map_path(@map) }
      end
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @map.destroy
    redirect_to maps_url, notice: t("helpers.message.map.destroyed"), status: :see_other
  end

  private

  def respond_show # Same response for maps#show and maps#shared
    respond_to do |format|
      format.html { render :show }
      format.style { render json: @map.style(url_for(Layer)) }
    end
  end

  def set_map
    @map = Map.find(params[:id])
    authorize @map
  end

  def new_map
    @map = Map.new
    @map.user_roles.new(user: current_user, role_type: :owner)
    authorize @map
  end

  def map_params
    params.require(:map).permit(:name, :default_latitude, :default_longitude, :default_zoom, :base_style_url,
      layers_attributes: [:name, :geometry_type, :map_id, :color, territory_category_ids: []])
  end

  def set_base_map_styles
    default_style = [[I18n.t("common.default_map_style"), ENV["DEFAULT_MAP_STYLE"] || "https://demotiles.maplibre.org/style.json"]]
    @map_styles = default_style + Rails.application.config.extra_map_styles.to_a
  end
end

app/views/maps/_name.html.erb
<%# locals: (map:) %>
<%# renders a form for a map name %>

<h2 id="<%= dom_id(map, :name) %>">
  <%= link_to map.name.presence || t(".map_with_no_name"), edit_map_path(map), class: "button button--extra-large button--link",
        data: {turbo_frame: "modal",
               restricted_target: "restricted", restricted_authorizations: %w[owner].to_json} %>
</h2>

app/views/maps/_sharing.html.erb
<%# locals: (map:) %>
<h2 class="form__header"><%= t(".header") %></h2>
<nav class="buttons-bar">
  <%= active_link_to UserRole.model_name.human(count: 2), map_user_roles_path(map), class: "button", class_active: "button--confirm", class_inactive: "button--link" %>
  <%= active_link_to MapToken.model_name.human(count: 2), map_map_tokens_path(map), class: "button", class_active: "button--confirm", class_inactive: "button--link" %>
</nav>

app/views/maps/_toolbar.html.erb
<%# locals: (map:) %>

<div class="map__toolbar__container">
  <div data-map-target="toolbarLeft">
  </div>
  <div>
    <button
      class="button button--confirm map__toolbar__add-button"
      hidden="hidden"
      data-map-target="addButton"
      data-action="map#toggleMode"
      data-restricted-target="restricted"
      data-restricted-authorizations="<%= %w[owner editor contributor].to_json %>">
    </button>
  </div>
  <div class="buttons-bar" data-map-target="toolbarRight">
    <div class="map__control__icon">
      <a download="<%= map.name + ".png" %>"
        data-action="map#exportMapAsImage"
        title="<%= t(".export_as_image") %>"
        aria-label="<%= t(".export_as_image") %>">
        <%= embedded_svg("export_as_image.svg") %>
      </a>
    </div>
    <div class="map__control__icon">
      <%= form_for map do |f| %>
        <%= f.hidden_field :default_latitude, data: {map_target: "defaultLatitude"} %>
        <%= f.hidden_field :default_longitude, data: {map_target: "defaultLongitude"} %>
        <%= f.hidden_field :default_zoom, data: {map_target: "defaultZoom"} %>
        <button data-action="map#setDefaultCenterZoom"
          title="<%= t(".set_center_and_zoom") %>"
          aria-label="<%= t(".set_center_and_zoom") %>">
          <%= embedded_svg "map-pin.svg" %>
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/maps/form.html.erb
<%# params: @map %>

<%= form_with(model: @map, id: dom_id(@map, :form), class: "form card__main-content") do |form| %>
  <% if @map.new_record? %>
    <h2 class="form__header"><%= t(".new") %></h2>
  <% end %>

  <div class="form__field form__field--large">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true %>

    <%= form.label :base_style_url %>
    <%= form.select :base_style_url, @map_styles %>
  </div>

  <% if @map.new_record? %><%# Also create the first layer %>
    <h3 class="form__header">
      <%= t(".first_layer") %>
    </h3>
    <%= form.fields_for :layers do |layer_form| %>
      <%= render "layers/form_contents", form: layer_form %>
    <% end %>
  <% end %>

<% end %>

<div class="card__footer-content">
  <%= submit_tag t(@map.new_record? ? :create : :update, scope: "helpers.submit.map"), class: "button button--confirm",
        form: dom_id(@map, :form), data: {turbo_frame: "_top"} %>

  <% if @map.persisted? && policy(@map).destroy? %>
    <%= button_to @map, method: :delete, class: "button button--delete button--lowercase",
          data: {turbo_confirm: t("common.confirm"), turbo_frame: "_top"} do %>
      <%= t("helpers.link.map.delete") %>
    <% end %>
  <% end %>
</div>

app/views/maps/index.html.erb
<%# params: @maps %>
<div class="container">
  <section class="section">
    <h2 class="section__title"><%= Map.model_name.human(count: 2) %></h2>
    <ul class="list">
      <% @maps.with_last_updated_row_id.includes(last_updated_row: :author).find_each do |map| %>
        <li class="list-element">
          <%= link_to map, class: "list-element__row list-element__row--link" do %>
            <div class="list-element__content">
              <h3 class="list-element__title"><%= map.name %></h3>
              <div class="list-element__description">
                <span><%= map.layers.size %> <%= Layer.model_name.human(count: map.layers.size).downcase %></span>
                <span><%= @maps_rows_count[map.id] %> <%= Row.model_name.human(count: @maps_rows_count[map.id]).downcase %></span>
                <span><%= t(".role_description.#{current_user.access_for_map(map).role_type}") %></span>
              </div>
              <div class="list-element__description">
                <%= map_updated_at_span(map.last_updated_row, map.last_updated_row&.author) %>
              </div>
            </div>
            <div class="icon-button icon-button--large list-element__row--link-button"><%= embedded_svg "chevron_droite.svg", class: "icon--tinted" %></div>
          <% end %>
        </li>
      <% end %>
    </ul>
    <% if current_user.anonymous? %>
      <div>
        <%= link_to t(".create_account"), new_user_registration_path, class: "button button--large button--confirm" %>
        <p><%= t("devise.registrations.log_in_instead_html", url: new_user_session_path) %></p>
      </div>
    <% else %>
      <%= link_to t("helpers.link.map.new"), new_map_path, class: "button button--large button--confirm", data: {turbo_frame: "modal"} %>
  <% end %>
  </section>
</div>

app/views/maps/show.html.erb
<%# params: @map, @role_type, @initially_active_layer %>
<% @initially_active_layer ||= @map.layers.ordered.first %>

<% content_for :header do %>
  <div class="header--start">
    <div class="buttons-bar buttons-bar--tight">
      <%= link_to maps_path, class: "button button--large button--text button--lowercase" do %>
        <%= embedded_svg "chevron_gauche.svg", class: "icon--narrow icon--tinted" %>
        <%= t(".all_maps") %>
      <% end %>
      <div class="buttons-segmented-bar"
           data-controller="segmented-bar" data-segmented-bar-dragbar-outlet=".map_document__container">
        <button class="button button--large button--text button--lowercase" data-segmented-bar-target="button" data-segmented-bar-value-param="table" data-action="segmented-bar#toggle">
          <%= t(".table") %>
        </button>
        <button class="button button--large button--text button--lowercase" data-segmented-bar-target="button" data-segmented-bar-value-param="map" data-action="segmented-bar#toggle">
          <%= t(".map") %>
        </button>
      </div>
    </div>
  </div>
  <div class="header--center">
    <%= render "name", map: @map %>
  </div>
  <div class="header--end"
       data-controller="presence-indicator"
       data-action="presence-tracker.connection-changed@document->presence-indicator#presenceChanged"
       data-presence-indicator-event-detail-attribute-value="connected"
       data-presence-indicator-on-title-value="<%= t("presence_indicator.connected") %>"
       data-presence-indicator-off-title-value="<%= t("presence_indicator.disconnected") %>">
    <div class="buttons-bar buttons-bar--tight">
      <% if policy(@map.user_roles.new).new? %>
        <%= link_to t(".share"), map_user_roles_path(@map), class: "button button--large button--text button--lowercase", data: {turbo_frame: "modal"} %>
      <% end %>
      <% if policy(@map.import_configurations.new).new? %>
        <%= link_to "Imports", map_import_operations_path(@map), class: "button button--large button--text button--lowercase", data: {turbo_frame: "modal"} %>
      <% end %>
      <%= render "header_menu_signed_in" %>
    </div>
    <div data-presence-indicator-target="indicator"></div>
  </div>
<% end %>

<% content_for(:footer)do %>
  <div hidden></div>
<% end %>

<% content_for :left_pane do %>
  <div
    class="map-data__container"
    data-controller="layer-selection">
    <div id="<%= dom_id(@map, "layers") %>">
      <% @map.layers.includes(:fields, :rows, :territory_categories).ordered.each_with_index do |layer, index| %>
        <% cache layer do %>
          <%= render layer, initially_active: layer == @initially_active_layer %>
          <% end %>
      <% end %>
    </div>
    <footer class="footer__layer-list">
      <%= link_to t("helpers.link.layer.new"), new_map_layer_path(@map), class: "button button--large button--confirm", data: {turbo_frame: "modal"} if policy(@map.layers.new).create? %>
    </footer>
  </div>
<% end %>

<% content_for :right_pane do %>
  <div class="map" data-map-target="map">
    <%= render "toolbar", map: @map %>
  </div>
<% end %>

<%= turbo_stream_from @map %>
<%= turbo_stream_i18n_from @map %>

<%= render "shared/dragbar", map: @map, role_type: @role_type, current_user_id: current_user_identifier %>