config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    devise_for :users, skip: :invitations, controllers: {registrations: "users/registrations", sessions: "users/sessions"}

    devise_scope :user do
      # Just the wanted subset of invitable routes
      get "/users/invitation/accept" => "devise/invitations#edit", :as => :accept_user_invitation
      put "/users/invitation" => "devise/invitations#update", :as => :user_invitation
    end

    unauthenticated do
      root "pages#presentation"
    end

    authenticated :user do
      root "maps#index", as: :user_root
    end

    resources :maps do
      resources :layers, only: [:new]
      resources :user_roles, only: [:index, :create, :update, :destroy], shallow: true
      resources :map_tokens, only: [:index, :create, :update, :destroy], shallow: true
      namespace :import do
        resources :operations, only: [:index, :new, :create, :show, :update, :destroy], shallow: true, namespace: :import
      end
    end
    resources :layers, except: [:index, :new] do
      resources :fields, only: [:new, :create, :edit, :update, :destroy], shallow: true
      resources :rows, only: [:new, :create, :show, :edit, :update, :destroy], shallow: true
      member do
        get "/mvt/:z/:x/:y/", action: :mvt
      end
    end

    resources :territory_categories, only: [:index, :show]
    resources :territories, only: [:show] do
      collection do
        get "search"
      end
    end

    get "/legal" => "pages#legal"
    get "/legal/conditions" => "pages#legal_conditions"
    get "/legal/data" => "pages#legal_data"
    get "/presentation" => "pages#presentation"
    get "/crowdsourcing" => "pages#use_case_crowdsourcing"
    get "share/:token", to: "maps#shared", as: "map_shared"
    get "layers/:id/geojson", to: redirect("layers/%{id}.geojson")
    get ".well-known/change-password", to: redirect("/users/edit")

    # URLs specific to the instance on cocarto.com
    get "/s/infolettre", to: redirect("https://buttondown.email/cocarto")
    get "/s/geodatadays", to: redirect("https://cocarto.com/share/dg4V524mFETB5Zoo")
    get "/s/commune_de_paris", to: redirect("https://cocarto.com/share/kxw8CL5tD42Do26z"), as: "share_commune_de_paris"
    get "/s/manifs_retraites", to: redirect("https://cocarto.com/share/xuzDBpYpv7jyH_aC"), as: "share_manifs_retraites"
    get "/s/gr20", to: redirect("https://cocarto.com/fr/share/f7iw5cSrm3sdCKRb"), as: "share_gr20"
    get "/s/ymca", to: redirect("https://cocarto.com/fr/share/TQxqzWYz9VYVBpgy")
    get "/s/ymca_m", to: redirect("https://cocarto.com/fr/layers/b00b15eb-c525-40ec-9e2a-1ea0ebf9330e/rows/new?token=TQxqzWYz9VYVBpgy")

    namespace :admin do
      resources :users, only: [:index, :destroy]
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  if Rails.env.development?
    mount GoodJob::Engine, at: "good_job"
    mount ActiveAnalytics::Engine, at: "analytics"
  else
    authenticate :user, ->(user) { user.admin? } do
      mount GoodJob::Engine, at: "good_job"
      mount ActiveAnalytics::Engine, at: "analytics"
    end
  end
end

app/models/layer.rb
# == Schema Information
#
# Table name: layers
#
#  id            :uuid             not null, primary key
#  geometry_type :enum             geometry, 0
#  name          :string
#  sort_order    :integer
#  style         :jsonb            not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  map_id        :uuid             not null
#
# Indexes
#
#  index_layers_on_map_id_and_sort_order  (map_id,sort_order) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (map_id => maps.id)
#
class Layer < ApplicationRecord
  include Mvt::LayerTiles
  include Mvt::LayerStyle

  # Constants
  COLORS = {
    blue: "#007AFF",
    cyan: "#32ADE6",
    indigo: "#5856D6",
    purple: "#AF52DE",
    green: "#34C759",
    brown: "#A2845E",
    pink: "#FF2D55",
    orange: "#FF9500"
  }

  # Attributes
  enum :geometry_type, {point: "point", line_string: "line_string", polygon: "polygon", territory: "territory"}, prefix: "geometry"

  # Relations
  belongs_to :map
  has_many :fields, -> { rank(:sort_order) }, dependent: :destroy, inverse_of: :layer
  has_many :rows, dependent: :delete_all, inverse_of: :layer
  has_and_belongs_to_many :territory_categories
  has_many :import_mappings, class_name: "Import::Mapping", dependent: :destroy

  # Query as scopes
  scope :with_last_updated_row_id, -> do
    left_outer_joins(:rows)
      .order("layers.id, rows.updated_at DESC NULLS LAST")
      .select("DISTINCT ON (layers.id) layers.*, rows.id as computed_last_updated_row_id")
  end
  belongs_to :last_updated_row, class_name: "Row", optional: true, foreign_key: "computed_last_updated_row_id" # rubocop:disable Rails/InverseOf

  scope :ordered, -> { order(sort_order: :asc) }

  # Hooks
  after_create_commit -> { broadcast_i18n_append_to map, target: dom_id(map, "layers"), locals: {initially_active: true} }
  after_update_commit -> do
    html = ApplicationController.render(StatsFooterComponent.new(layer: self), layout: false)
    broadcast_i18n_replace_to map, target: dom_id(self, :stats), html: html
    broadcast_i18n_replace_to map, target: dom_id(self, :header), partial: "layers/layer_header"
  end
  after_destroy_commit do
    broadcast_remove_to map
    MapUpdateChannel.broadcast_to(map, deleted_layer_id: dom_id(self))
  end

  after_touch -> { clear_memoized_fields }

  # Memoize: avoid querying the database when looking up a field by its ID or type
  def fields_by_id
    @fields_by_id ||= fields.index_by(&:id)
  end

  # Group the fields by type without querying the database (unlike `fields.type_*` methods)
  def fields_by_type
    @fields_by_type ||= fields
      .group_by(&:field_type)
      .tap { |result| result.default = [].freeze }
  end

  def clear_memoized_fields
    @fields_by_id = nil
    @fields_by_type = nil
  end

  # Helper to preload rows fields values
  def rows_with_fields_values = rows.with_fields_values(self)

  def geometry_type_description
    Layer.human_attribute_name("geometry_type_description.#{geometry_type}")
  end

  def color
    style["color"] || COLORS[:blue]
  end

  def color=(new_color)
    style["color"] = new_color
  end

  # Dynamic Fields Associations
  # return all the names for the dynamic associations.
  # They can be used in `.includes` or `.preload`/`.eager_load` for the rows of this layer.
  def fields_association_names
    fields_by_type["territory"].map(&:association_name)
  end

  # Convert geometry from a collection to a single feature
  def coerced_geometry(geometry, errors: nil)
    return geometry unless geometry.is_a?(RGeo::GeoJSON::FeatureCollection) || geometry.is_a?(RGeo::Feature::GeometryCollection)

    if geometry.unsafe_size > 1 # See RGeo::ImplHelper::ValidityCheck; we don’t want to check for validity here.
      if geometry_line_string?
        errors&.add(:geometry, :multiple_line_strings_merged)
        RGEO_FACTORY.line_string(geometry.flat_map(&:points))
      else
        errors&.add(:geometry, :multiple_items)
        geometry.first
      end
    else
      geometry.first
    end
  end
end

app/controllers/layers_controller.rb
require "securerandom"

class LayersController < ApplicationController
  include Ordering
  before_action :authenticate_user!
  before_action :set_layer, only: %i[show edit update destroy]

  def show
    respond_to do |format|
      format.html { render @layer, locals: {initially_active: true, order: row_order} }
      format.any(*ImportExport::EXPORTERS.keys) do
        allow_origin_everywhere
        data = ImportExport.export(@layer, request.format.to_sym)
        send_data data, filename: "#{@layer.name}.#{request.format.to_sym}", type: Mime[request.format]
      end
    end
  end

  def new
    map = current_user.maps.find(params["map_id"])
    @layer = authorize map.layers.new
    render :form
  end

  def edit
    render :form
  end

  def create
    map = current_user.maps.includes(:layers).find(layer_params["map_id"])

    layer = authorize map.layers.new(layer_params)
    if layer.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: [] }
        format.html { redirect_to layer }
      end
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render :form, status: :unprocessable_entity
    end
  end

  def update
    if @layer.update(layer_params)
      @layer.broadcast_i18n_replace_to @layer.map
      respond_to do |format|
        format.turbo_stream { render turbo_stream: [] }
        format.html { redirect_to @layer }
      end
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @layer.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: [] }
      format.html { redirect_to @layer.map, notice: t("helpers.message.layer.destroyed"), status: :see_other }
    end
  end

  def mvt
    # MVT is a vector tile format used to render features on a map
    # A tile in the xyz is defined by its zoom level (z) and position on the map
    # This functions returs the MVT tile of the current layer
    layer = authorize Layer.find(params[:id])
    x, y, z = params[:x], params[:y], params[:z]
    tile = Rails.cache.fetch([layer, "mvt", x, y, z]) { layer.as_mvt(x, y, z) }
    send_data tile
  end

  private

  def set_layer
    @layer = authorize Layer.includes(:map, :import_mappings, rows: :territory, fields: :territory_categories).find(params[:id])
  end

  def layer_params
    params.require(:layer).permit(:name, :geometry_type, :map_id, :color, territory_category_ids: [])
  end

  def allow_origin_everywhere
    headers["Access-Control-Allow-Origin"] = "*"
    headers["Access-Control-Allow-Methods"] = "GET OPTIONS"
    headers["Access-Control-Allow-Headers"] = "*"
  end
end

app/views/layers/_form_contents.html.erb
<%# locals: (form:) %>
<% layer = form.object %>

<div data-controller="layer-form">
  <div class="form__field form__field--large">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true,
          placeholder: (layer.persisted? ? layer.geometry_type_description : nil) %>
  </div>

  <h4 class="form__header"><%= Layer.human_attribute_name(:color) %></h4>
  <div class="form__field form__field--large layer-form__color-field">
    <% Layer::COLORS.each do |key, rgb| %>
      <div class="form__field form__field--large form__field--inline">
        <%= form.radio_button :color, rgb, data: {"layer-form-color-param": rgb, "layer-form-target": "colorInput", action: "layer-form#colorSelected"} %>
        <%= form.label :color, t(key, scope: "colors"), value: rgb %>
      </div>
    <% end %>
  </div>

  <% if layer.new_record? %>
    <h4 class="form__header"><%= Layer.human_attribute_name(:geometry_type) %></h4>
    <div class="form__field form__field--large form__field--inline layer-form__type-field">
      <% Layer.geometry_types.keys.each do |type| %>
        <%= form.label "geometry_type_#{type}" do %>
          <%= form.radio_button :geometry_type, type, checked: type == "point", data: {"layer-form-type-param": type, action: "layer-form#typeSelected"} %>
          <div class="layer-form__type-option">
            <div data-layer-form-target="icon"><%= embedded_svg "#{type}.svg" %></div>
            <%= Layer.human_attribute_name(type, count: 2).capitalize %>
          </div>
        <% end %>
      <% end %>
    </div>

    <h4 class="form__header" hidden data-layer-form-target="territoryCategories"><%= TerritoryCategory.model_name.human(count: 2) %></h4>
    <div class="form__field" hidden data-layer-form-target="territoryCategories">
      <%= form.collection_check_boxes :territory_category_ids, TerritoryCategory.all, :id, :to_s do |b| %>
        <%= b.label(class: "form__field form__field--large form__field--inline") { b.check_box + b.text } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layers/_layer.html.erb
<%# locals: (layer:, initially_active: false, order: Ordering::Order.new) %>

<turbo-frame id="<%= dom_id(layer) %>">
<div
  class="layer-container"
  data-controller="layer"
  data-layer-id-value="<%= dom_id(layer) %>"
  data-action="layer:row_focused->map#selectFeature"
  data-layer-layer-outlet=".layer-container.is-active"
  data-layer-map-outlet=".map_document__container"
  data-layer-add-feature-text-value="<%= t("common.add_geometry.#{layer.geometry_type}") %>"
  data-layer-geometry-type-value="<%= layer.geometry_type %>"
  data-layer-initially-active-value="<%= initially_active %>">

  <%= render "layers/layer_header", layer: layer %>
  <div id="<%= dom_id(layer, :updates) %>" hidden></div>

  <div class="layer-contents">
    <%= render "layers/rows", layer: layer, order: order %>

    <%= render "rows/new", row: Row.new(layer: layer) %>

    <footer class="layer-footer">
      <div class="buttons-bar">
        <%= link_to new_map_import_operation_path(layer.map, layer_id: layer), title: t("helpers.link.layer.import"),
              class: "icon-button icon-button--double-bordered icon-button--small",
              data: {turbo_frame: "modal",
                     restricted_target: "restricted", restricted_authorizations: '["owner", "editor", "contributor"]'} do %> <%# Cf policy(row).new? %>
          <%= embedded_svg "file-up.svg" %>
        <% end %>
        <div class="dropdown" data-controller="dropdown" data-action="click->dropdown#toggle" data-dropdown-target="trigger">
          <button class="icon-button icon-button--double-bordered icon-button--small" title="<%= t("helpers.link.layer.export") %>">
            <%= embedded_svg "file-down.svg" %>
          </button>
          <div class="dropdown__content" data-dropdown-target="content">
            <div class="card__main-content">
              <%= link_to t("helpers.link.layer.export_geojson"), layer_path(layer, format: :geojson), download: "#{layer.name}.geojson" %>
              <%= link_to t("helpers.link.layer.export_csv"), layer_path(layer, format: :csv), download: "#{layer.name}.csv" %>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>
</div>
</turbo-frame>

app/views/layers/_layer_header.html.erb
<%# locals: (layer:) %>

<header class="layer-header" id="<%= dom_id(layer, :header) %>" data-action="click->layer#toggleTable:self">
  <%= link_to edit_layer_path(layer), class: "layer-header__name-button", title: t("common.edit"),
        data: {turbo_frame: "modal",
               restricted_target: "restricted", # cf LayerPolicy#update?
               restricted_authorizations: %w[owner editor].to_json} do %>
    <div class="layer-header__icon">
      <%= embedded_svg "#{layer.geometry_type}.svg", class: "icon--regular", style: "color: #{layer.color}" %>
    </div>

    <%= layer.name.presence || layer.geometry_type_description %>
  <% end %>

  <div class="buttons-bar buttons-bar--tight">
    <% if layer.rows.present? %>
      <button class="layer-header__icon button layer-header__button--link"
        title="<%= t(".center_on_layer") %>"
        data-action="click->map#center"
        <%# This makes an N+1 request per-layer. %>
        <%# FIXME: refactor this into some JS dynamically fetching the bounding box when the button is clicked. %>
        data-map-bounds-param="<%= Prosopite.pause do layer.rows.bounding_box.to_json end %>">
        <%= embedded_svg "frame.svg", class: "icon--small" %>
      </button>
    <% end %>
    <button class="layer-header__icon button layer-header__button--link"
      title="<%= t(".hide_layer_on_map") %>"
      data-layer-target="hideButton"
      data-action="click->layer#hideOnMap">
      <%= embedded_svg "eye.svg", class: "icon--small" %>
    </button>
    <button class="layer-header__icon button layer-header__button--link"
      title="<%= t(".show_layer_on_map") %>"
      data-layer-target="showButton"
      data-action="click->layer#showOnMap"
      hidden>
      <%= embedded_svg "eye-off.svg", class: "icon--small" %>
    </button>
    <button
      class="layer-header__icon button layer-header__toggle-button"
      title="<%= t(".toggle_layer") %>"
      data-action="layer#toggleTable">
      <%= embedded_svg "chevron_droite.svg", class: "icon--regular icon--tinted layer__indicator" %>
    </button>
  </div>
</header>

app/views/layers/_rows.html.erb
<%# locals: (layer:, order: nil) %>
<%# renders a full table of editable rows for a layer %>

<table class="layer-table">
  <thead class="layer-table__thead">
    <tr class="layer-table__tr">
      <%# calculated columns first %>
      <% if layer.geometry_territory? %>
        <th class="layer-table__th layer-table__th--field">
          <div class="layer-table-th__contents layer-table-th__contents--resizable">
            <%= Territory.model_name.human %>
          </div>
        </th>
        <th class="layer-table__th layer-table__th--stats"><div class="layer-table-th__contents"><%= t("common.territory_code") %></div></th>
      <% elsif layer.geometry_point? %>
        <th class="layer-table__th layer-table__th--stats"><div class="layer-table-th__contents"><%= t("common.longitude") %></div></th>
        <th class="layer-table__th layer-table__th--stats"><div class="layer-table-th__contents"><%= t("common.latitude") %></div></th>
      <% elsif layer.geometry_line_string? %>
        <th class="layer-table__th layer-table__th--stats"><div class="layer-table-th__contents"><%= t("common.length") %></div></th>
      <% elsif layer.geometry_polygon? %>
        <th class="layer-table__th layer-table__th--stats"><div class="layer-table-th__contents"><%= t("common.area") %></div></th>
      <% end %>

      <%= render layer.fields, order: order %>

      <%= render Field.new(layer: layer) %>
    </tr>
  </thead>
  <tbody id="<%= dom_id(layer, :rows) %>">
    <% rows = Prosopite.pause do # technically this is a N+1 (one for each layer), but we actually *want* this.
         layer.rows_with_fields_values.order(order.sql).load
       end %>
    <%= render partial: "rows/row_tr", collection: rows, as: :row, cached: ->(row) { [row, row.layer] } %>
  </tbody>
  <tfoot>
    <%= render StatsFooterComponent.new(layer: layer) %>
  </tfoot>
</table>

app/views/layers/form.html.erb
<%# params: @layer %>

<%= form_with(model: @layer, id: dom_id(@layer, :form), class: "form card__main-content") do |form| %>
  <%= form.hidden_field :map_id %>
  <% if @layer.new_record? %>
    <h2 class="form__header"><%= t(".new") %></h2>
  <% end %>
  <%= render "form_contents", form: form %>
<% end %>

<div class="card__footer-content">
  <%= submit_tag t(@layer.new_record? ? :create : :update, scope: "helpers.submit.layer"), class: "button button--confirm",
        form: dom_id(@layer, :form), data: {turbo_frame: "_top"} %>

  <% if @layer.persisted? && policy(@layer).destroy? %>
    <%= button_to @layer, method: :delete, class: "button button--delete button--lowercase",
          data: {turbo_confirm: t("common.confirm"), turbo_frame: "_top"} do %>
      <%= t("helpers.link.layer.delete") %>
    <% end %>
  <% end %>
</div>