config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    devise_for :users, skip: :invitations, controllers: {registrations: "users/registrations", sessions: "users/sessions"}

    devise_scope :user do
      # Just the wanted subset of invitable routes
      get "/users/invitation/accept" => "devise/invitations#edit", :as => :accept_user_invitation
      put "/users/invitation" => "devise/invitations#update", :as => :user_invitation
    end

    unauthenticated do
      root "pages#presentation"
    end

    authenticated :user do
      root "maps#index", as: :user_root
    end

    resources :maps do
      resources :layers, only: [:new]
      resources :user_roles, only: [:index, :create, :update, :destroy], shallow: true
      resources :map_tokens, only: [:index, :create, :update, :destroy], shallow: true
      namespace :import do
        resources :operations, only: [:index, :new, :create, :show, :update, :destroy], shallow: true, namespace: :import
      end
    end
    resources :layers, except: [:index, :new] do
      resources :fields, only: [:new, :create, :edit, :update, :destroy], shallow: true
      resources :rows, only: [:new, :create, :show, :edit, :update, :destroy], shallow: true
      member do
        get "/mvt/:z/:x/:y/", action: :mvt
      end
    end

    resources :territory_categories, only: [:index, :show]
    resources :territories, only: [:show] do
      collection do
        get "search"
      end
    end

    get "/legal" => "pages#legal"
    get "/legal/conditions" => "pages#legal_conditions"
    get "/legal/data" => "pages#legal_data"
    get "/presentation" => "pages#presentation"
    get "/crowdsourcing" => "pages#use_case_crowdsourcing"
    get "share/:token", to: "maps#shared", as: "map_shared"
    get "layers/:id/geojson", to: redirect("layers/%{id}.geojson")
    get ".well-known/change-password", to: redirect("/users/edit")

    # URLs specific to the instance on cocarto.com
    get "/s/infolettre", to: redirect("https://buttondown.email/cocarto")
    get "/s/geodatadays", to: redirect("https://cocarto.com/share/dg4V524mFETB5Zoo")
    get "/s/commune_de_paris", to: redirect("https://cocarto.com/share/kxw8CL5tD42Do26z"), as: "share_commune_de_paris"
    get "/s/manifs_retraites", to: redirect("https://cocarto.com/share/xuzDBpYpv7jyH_aC"), as: "share_manifs_retraites"
    get "/s/gr20", to: redirect("https://cocarto.com/fr/share/f7iw5cSrm3sdCKRb"), as: "share_gr20"
    get "/s/ymca", to: redirect("https://cocarto.com/fr/share/TQxqzWYz9VYVBpgy")
    get "/s/ymca_m", to: redirect("https://cocarto.com/fr/layers/b00b15eb-c525-40ec-9e2a-1ea0ebf9330e/rows/new?token=TQxqzWYz9VYVBpgy")

    namespace :admin do
      resources :users, only: [:index, :destroy]
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  if Rails.env.development?
    mount GoodJob::Engine, at: "good_job"
    mount ActiveAnalytics::Engine, at: "analytics"
  else
    authenticate :user, ->(user) { user.admin? } do
      mount GoodJob::Engine, at: "good_job"
      mount ActiveAnalytics::Engine, at: "analytics"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Pundit handles the authorization policies
  include Pundit::Authorization
  # Note: we can’t use only: :action or except: :action in the after_action hooks below because of raise_on_missing_callback_actions.
  # However, we still want these hooks by default for all regular routes.
  after_action :verify_authorized, unless: -> { _1.action_name == "index" }
  after_action :verify_policy_scoped, if: -> { _1.action_name == "index" }
  after_action :record_page_view

  around_action :switch_locale, # make sure set_locale is first so that error messages are localized
    :restore_anonymous_session,
    :set_sentry_user,
    :rescue_unauthorized

  def default_url_options
    {locale: I18n.locale}
  end

  def switch_locale(&action)
    locale = params.delete(:locale) || http_accept_language.compatible_language_from(I18n.available_locales)
    I18n.with_locale(locale, &action)
  end

  def restore_anonymous_session # See MapTokenAuthenticatable
    if warden.authenticated? && current_user.anonymous?
      current_user.store_tokens_array_in_session(session) # restore anonymous map tokens
    end
    yield
  end

  def set_sentry_user
    # Note: this is where we call `current_user` for the first time in each request.
    # It has side effects!
    # (e.g. if the found user is invited but not signed up yet)
    # See the Devise::FailureApp for flashes and redirections.
    if warden.authenticated?
      Sentry.set_user(id: helpers.current_user_identifier)
    end
    yield
  end

  def rescue_unauthorized
    yield
  rescue Pundit::NotAuthorizedError
    flash[:alert] = t("common.user_not_authorized")
    if request.get? && request.referer != request.url
      redirect_back_or_to(root_path)
    else
      head :not_found
    end
  end

  def record_page_view
    if response.content_type&.start_with?("text/html")
      ActiveAnalytics.record_request(request)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_identifier
    current_user.anonymous? ? current_user.anonymous_tag : current_user.id
  end

  # Embeds the svg file directly in the dom
  # This allows to use `currentColor` attribute and style the file with CSS
  # Currently accepted options that are passed to the <svg> tag:
  # - class
  # - style
  def embedded_svg(filename, **options)
    Rails.cache.fetch(["svg", filename, options]) {
      file = Rails.root.join("app", "assets", "images", filename).read
      doc = Nokogiri::HTML::DocumentFragment.parse file
      svg = doc.at_css "svg"
      svg["class"] = options[:class] if options[:class].present?
      svg["style"] = options[:style] if options[:style].present?

      doc.to_html.html_safe # rubocop:disable Rails/OutputSafety
    }
  end

  def link_with_icon text, path, filename, **options
    link_to path, options do
      embedded_svg(filename).concat(text)
    end
  end

  def anchor_link(name, html_options = nil, &)
    anchor = name.parameterize
    link_to(name, "##{anchor}", {id: anchor}.merge(html_options || {}), &)
  end

  def i18n_key_value_pair(field, value)
    value = auto_link(value.to_s, html: {target: "_blank", rel: "noopener"})
    t("common.i18n_key_value_pair", field: field.display_label, value: value.presence || t("common.no_value")).html_safe
  end

  def map_updated_at_span(record, author = nil)
    return if record.nil?

    text = if author.present?
      t("common.updated_at_by", date: time_ago_in_words(record.updated_at), user: author.display_name)
    else
      t("common.updated_at", date: time_ago_in_words(record.updated_at))
    end
    tag.span text, title: l(record.updated_at, format: :long)
  end

  def mailto_contact(name = nil, html_options = nil, &)
    mail_to(t("common.app.contact_email"), name, html_options, &)
  end
end

app/views/application/_favicon.html.erb
<%# locals: () %>

<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#4D7A5D">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="cocarto">

app/views/application/_flash.html.erb
<div id="flash" class="flash__container" data-controller="flash" data-action="click->flash#clear">
  <% flash.each do |flash_type, message| %>
    <div class="<%= class_names("message", "flash__item", "message--#{flash_type}") %>" data-flash-target="flash">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/application/_footer.html.erb
<%# locals: () %>

<footer class="footer">
  <section class="container footer__container">
    <div class="footer__column">
      <h3><%= t("common.app.title") %></h3>
      <ul>
        <li><%= link_to t(".presentation"), presentation_path %></li>
        <li><%= link_to t(".pricing"), presentation_path(anchor: "combien-ca-coute") %></li>
        <li><%= link_to t(".source_code"), "https://gitlab.com/CodeursEnLiberte/cocarto" %></li>
      </ul>
    </div>

    <div class="footer__column">
      <h3><%= t(".use_cases") %></h3>
      <ul>
        <li><%= link_to t(".crowdsourcing"), crowdsourcing_path %></li>
        <!-- li>Tableur</li -->
        <!-- li>Qualité des données</li -->
      </ul>
    </div>

    <div class="footer__column">
      <h3><%= t(".resources") %></h3>
      <ul>
        <li><%= link_to t(".privacy"), legal_data_path %></li>
        <li><%= link_to t(".terms_of_use"), legal_conditions_path %></li>
        <li><%= link_to t(".legal_notice"), legal_path %></li>
      </ul>
    </div>
  </section>
</footer>

app/views/application/_header.html.erb
<%# locals: (header_mode:) %>
<%# possible values: :app, :cartouche %>

<% header_mode ||= :app %>

<header class="header__container">
  <div class="<%= class_names("header", (header_mode == :app) ? "header--app" : "header--large") %>">
    <%= content_for?(:header) ? yield(:header) : render("header_default", header_mode: header_mode) %>
  </div>
</header>

app/views/application/_header_default.html.erb
<%# locals: (header_mode:) %>
<%# possible values: :app, :cartouche %>

<div class="header--start">
  <% if header_mode == :cartouche %>
    <%= image_tag("cartouche_color.svg", class: "header__cartouche") %>
  <% else %>
    <h1>
      <%= link_to root_path, class: "header__logo", title: t("common.app.title") do %>
        <%= embedded_svg("cocarto_logotype.svg") %>
      <% end %>
    </h1>
  <% end %>
</div>

<div class="header--end">
  <% if user_signed_in? %>
    <%= render "header_menu_signed_in" %>
  <% else %>
    <%= render "header_menu_signed_out" %>
  <% end %>
</div>

app/views/application/_header_menu_signed_in.html.erb
<%# locals: () %>

<div class="dropdown" data-controller="dropdown" data-action="click->dropdown#toggle" data-dropdown-target="trigger">
  <button class="button button--large button--text" title="<%= t("common.settings") %>">
    <%= current_user.display_name %>
    <%= embedded_svg "chevron_droite.svg", class: "icon--smaller icon--tinted dropdown__indicator" %>
  </button>
  <div class="dropdown__content" data-dropdown-target="content">
    <div class="card__main-content">
      <%= link_to "Français", url_for(locale: :fr), class: "dropdown__item" %>
      <%= link_to "English", url_for(locale: :en), class: "dropdown__item" %>
      <%= link_to t("layouts.menu.preferences"), edit_user_registration_url, class: "dropdown__item" unless current_user.anonymous? %>
    </div>
    <div class="card__footer-content">
      <% if current_user.anonymous? %>
        <%= link_to t("layouts.menu.sign_up"), new_user_registration_path, class: "button button--confirm" %>
        <%= link_to t("layouts.menu.sign_in"), new_user_session_path, class: "button button--link" %>
      <% else %>
        <%= button_to t("layouts.menu.sign_out"), destroy_user_session_path, method: :delete, class: "button button--delete button--lowercase" %>
      <% end %>
    </div>
  </div>
</div>

app/views/application/_header_menu_signed_out.html.erb
<%# locals: () %>

<div class="buttons-bar buttons-bar--loose">
  <%= link_to t("layouts.menu.sign_in"), new_user_session_path, class: "button button--large button--link" %>
  <%= link_to t("layouts.menu.sign_up"), new_user_registration_path, class: "button button--large button--confirm" %>
  <div class="dropdown" data-controller="dropdown">
    <button class="icon-button icon-button--double-bordered icon-button--large icon-button--dimmed"
            role="button" aria-haspopup="menu" aria-label="<%= t("layouts.menu.change_language") %>" aria-controls="languages-selector"
            data-action="click->dropdown#toggle" data-dropdown-target="trigger">
      <%= embedded_svg "language-selector.svg", class: "icon--tinted" %>
    </button>
    <div id="languages-selector" class="dropdown__content" data-dropdown-target="content">
      <div class="card__main-content card__main-content--slim">
        <%= link_to "English", url_for(locale: :en), class: "dropdown__item" %>
        <%= link_to "Français", url_for(locale: :fr), class: "dropdown__item" %>
      </div>
    </div>
  </div>
</div>

app/views/application/_sentry.html.erb
<%# locals: () %>

<%# Sentry configuration for javascript (see also _sentry.html.erb for ruby configuration) %>
<% return unless Rails.env.production? || ENV.include?("COCARTO_DEBUG_SENTRY") %>
<% return if ENV["SENTRY_PUBLIC_KEY"].blank? %>

<script src="https://js.sentry-cdn.com/<%= ENV.fetch("SENTRY_PUBLIC_KEY") %>.min.js" crossorigin="anonymous"></script>
<script>
  Sentry.onLoad(function() {
    Sentry.init({
      release: "<%= (ENV.fetch("CONTAINER_VERSION") { "dev" }) %>", <%# Set by Scalingo, see https://doc.scalingo.com/platform/app/environment#runtime-environment-variables %>
      environment: "<%= Rails.env %>",
      sampleRate: 1.0, <%# Send all errors %>
      tracesSampleRate: 0.05 <%# Send only 5% of transactions %>
    });
    Sentry.setUser({ id: "<%= current_user&.id %>" });
  });
</script>