config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    devise_for :users, skip: :invitations, controllers: {registrations: "users/registrations", sessions: "users/sessions"}

    devise_scope :user do
      # Just the wanted subset of invitable routes
      get "/users/invitation/accept" => "devise/invitations#edit", :as => :accept_user_invitation
      put "/users/invitation" => "devise/invitations#update", :as => :user_invitation
    end

    unauthenticated do
      root "pages#presentation"
    end

    authenticated :user do
      root "maps#index", as: :user_root
    end

    resources :maps do
      resources :layers, only: [:new]
      resources :user_roles, only: [:index, :create, :update, :destroy], shallow: true
      resources :map_tokens, only: [:index, :create, :update, :destroy], shallow: true
      namespace :import do
        resources :operations, only: [:index, :new, :create, :show, :update, :destroy], shallow: true, namespace: :import
      end
    end
    resources :layers, except: [:index, :new] do
      resources :fields, only: [:new, :create, :edit, :update, :destroy], shallow: true
      resources :rows, only: [:new, :create, :show, :edit, :update, :destroy], shallow: true
      member do
        get "/mvt/:z/:x/:y/", action: :mvt
      end
    end

    resources :territory_categories, only: [:index, :show]
    resources :territories, only: [:show] do
      collection do
        get "search"
      end
    end

    get "/legal" => "pages#legal"
    get "/legal/conditions" => "pages#legal_conditions"
    get "/legal/data" => "pages#legal_data"
    get "/presentation" => "pages#presentation"
    get "/crowdsourcing" => "pages#use_case_crowdsourcing"
    get "share/:token", to: "maps#shared", as: "map_shared"
    get "layers/:id/geojson", to: redirect("layers/%{id}.geojson")
    get ".well-known/change-password", to: redirect("/users/edit")

    # URLs specific to the instance on cocarto.com
    get "/s/infolettre", to: redirect("https://buttondown.email/cocarto")
    get "/s/geodatadays", to: redirect("https://cocarto.com/share/dg4V524mFETB5Zoo")
    get "/s/commune_de_paris", to: redirect("https://cocarto.com/share/kxw8CL5tD42Do26z"), as: "share_commune_de_paris"
    get "/s/manifs_retraites", to: redirect("https://cocarto.com/share/xuzDBpYpv7jyH_aC"), as: "share_manifs_retraites"
    get "/s/gr20", to: redirect("https://cocarto.com/fr/share/f7iw5cSrm3sdCKRb"), as: "share_gr20"
    get "/s/ymca", to: redirect("https://cocarto.com/fr/share/TQxqzWYz9VYVBpgy")
    get "/s/ymca_m", to: redirect("https://cocarto.com/fr/layers/b00b15eb-c525-40ec-9e2a-1ea0ebf9330e/rows/new?token=TQxqzWYz9VYVBpgy")

    namespace :admin do
      resources :users, only: [:index, :destroy]
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  if Rails.env.development?
    mount GoodJob::Engine, at: "good_job"
    mount ActiveAnalytics::Engine, at: "analytics"
  else
    authenticate :user, ->(user) { user.admin? } do
      mount GoodJob::Engine, at: "good_job"
      mount ActiveAnalytics::Engine, at: "analytics"
    end
  end
end

app/models/field.rb
# == Schema Information
#
# Table name: fields
#
#  id                 :uuid             not null, primary key
#  display_in_tooltip :boolean          default(TRUE), not null
#  enum_values        :string           is an Array
#  field_type         :enum             not null
#  label              :string
#  locked             :boolean          default(FALSE), not null
#  sort_order         :integer
#  text_is_long       :boolean          default(FALSE), not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  layer_id           :uuid             not null
#
# Indexes
#
#  index_fields_on_layer_id_and_sort_order  (layer_id,sort_order) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (layer_id => layers.id)
#
class Field < ApplicationRecord
  # Attributes
  enum :field_type, {text: "text", float: "float", integer: "integer", territory: "territory", date: "date", boolean: "boolean", css_property: "css_property", enum: "enum", files: "files"}, prefix: :type
  attr_readonly :field_type

  # Ordering
  include RankedModel
  ranks :sort_order, with_same: :layer_id
  attribute :sort_order, default: :last

  # Relations
  belongs_to :layer, touch: true
  has_and_belongs_to_many :territory_categories
  has_many :import_mappings, class_name: "Import::Mapping", inverse_of: :reimport_field, foreign_key: :reimport_field_id, dependent: :nullify

  # Validations
  validates :field_type, presence: true
  validates :text_is_long, inclusion: [true, false]
  validates :locked, inclusion: [true, false]
  validates :display_in_tooltip, inclusion: [true, false]

  # Type-specific validations
  validates :enum_values, presence: true, if: -> { type_enum? }

  # Hooks
  after_create_commit -> do
    broadcast_before_to layer.map, target: dom_id(layer, :new_field)
    layer.rows.each do |row|
      content = ApplicationController.render(FieldValueComponent.new(field: self, value: nil, row: row, form_prefix: :inline_form), layout: false)
      html = ApplicationController.render(FieldTdComponent.new(field: self).with_content(content), layout: false)
      broadcast_i18n_before_to(layer.map, target: dom_id(row, "actions"), html: html)
    end
  end

  after_update_commit -> do
    broadcast_replace_to layer.map
    needs_rows_broadcast = type_enum? && enum_values_previously_changed? || type_text? && text_is_long_previously_changed? || locked_previously_changed?
    if needs_rows_broadcast
      # issue #200: update all the rows so that the <select> options reflect the available enum values.
      layer.rows_with_fields_values.each do |row|
        content = ApplicationController.render(FieldValueComponent.new(field: self, value: row.fields_values[self], row: row, form_prefix: :inline_form), layout: false)
        html = ApplicationController.render(FieldTdComponent.new(field: self).with_content(content), layout: false)
        target = "##{dom_id(row)} .#{dom_id(self)}"
        # note: we need to use the `targets:` param when using `replace_to` to a css selector.
        broadcast_i18n_replace_to(layer.map, target: nil, targets: target, html: html)
      end
    end
  end

  after_destroy_commit -> do
    return if layer.destroyed?

    broadcast_remove_to layer.map
    Turbo::StreamsChannel.broadcast_remove_to layer.map, targets: ".#{dom_id(self)}"
  end

  # Type-specific coercion
  def enum_values=(new_values)
    super(new_values&.compact_blank&.uniq)
  end

  # HTML only speaks in strings
  # It casts to its native representation
  def cast(value)
    if type_territory?
      value = value.id if value.is_a?(Territory)
      if (territory_id = known_territories_by_code[value]) # value is a territory code
        territory_id
      elsif known_territories_by_code.has_value?(value) # value is a territory id
        value
      end
    elsif type_files?
      return nil unless value.is_a?(Array)
      value.filter_map do |file|
        if file == "_empty"
          nil
        elsif file.is_a?(String)
          # We’re using ActiveStorage direct upload in the frontend, which means the blobs are *already* there when we set the row values.
          # It’s easier here: file is a (signed) blob identifier, no matter whether it’s a new or existing attachment.
          #
          # Without direct upload, file would be an ActionDispatch::Http::UploadedFile, and we would have to upload it from here (with ActiveStorage::Blob.create_and_upload).
          ActiveStorage::Blob.find_signed(file)&.id
        end
      end
    elsif type_css_property? && label == "stroke-width"
      ActiveModel::Type.lookup(:integer).cast(value)
    elsif active_model
      active_model.cast(value)
    else
      value
    end
  end

  # Memoize territory codes and ids.
  # Useful when importing a lot of Rows, each with a territory code. (e.g. an “commune insee code” column)
  # This works because the Field object itself is kept around during import; see also Layer#fields_by_id for a similar optimization.
  def known_territories_by_code
    # Note: the returned hash maps the code to the id.
    # Lookup by code is O(log(n)); lookup by id is linear, but still faster than a SQL query everytime.
    @known_territories ||= Territory.where(territory_category: territory_categories).pluck(:code, :id).to_h
  end

  def active_model
    active_model_type = {
      "text" => :string,
      "float" => :float,
      "integer" => :integer,
      "date" => :date,
      "boolean" => :boolean
    }[field_type]

    ActiveModel::Type.lookup(active_model_type) if active_model_type
  end

  def sum
    case field_type
    when "float", "integer"
      layer.rows.sum(Arel.sql("(values->>'#{id}')::numeric"))
    when "boolean"
      layer.rows.where("(values->>'#{id}')::bool").size
    end
  end

  def display_label
    label.presence || Field.human_attribute_name("field_types.#{field_type}")
  end

  # Can this field have multiple values (array, attached files…)
  def multiple? = type_files?

  def numeric? = ["integer", "float"].include?(field_type)

  include FieldValuesAssociations::AssociationName
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_field, only: %i[edit update destroy]

  def new
    @field = authorize Field.new(layer: Layer.find(params[:layer_id]))
    render :form
  end

  def edit
    @order_direction = params[:order_direction]
    render :form
  end

  def create
    @field = authorize Field.new(field_params)

    if @field.save
      flash.now[:notice] = t("helpers.message.field.created", name: @field.label)
    else
      flash.now[:alert] = @field.errors.first.full_message
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace(helpers.dom_id(@field.layer, :new_field), Field.new(layer: @field.layer)) # Clear the “new_field” form
        ]
      end
      format.html { redirect_to @field.layer }
    end
  end

  def update
    if @field.update(field_params)
      flash.now[:notice] = t("helpers.message.field.updated")
    else
      flash.now[:alert] = @field.errors.first.full_message
    end

    respond_to do |format|
      format.turbo_stream { render turbo_stream: [] }
      format.html { redirect_to @field.layer }
    end
  end

  def destroy
    if @field.destroy
      flash.now[:notice] = t("helpers.message.field.destroyed")
    else
      flash.now[:alert] = @field.errors.first.full_message
    end

    respond_to do |format|
      format.turbo_stream { render turbo_stream: [] }
      format.html { redirect_to @field.layer, status: :see_other }
    end
  end

  private

  def set_field
    @field = authorize Field.includes(:territory_categories, layer: [:map, :rows, :fields]).find(params[:id])
  end

  def field_params
    params.require(:field).permit(:label, :layer_id, :locked, :field_type, :display_in_tooltip, :text_is_long, enum_values: [], territory_category_ids: [])
  end
end

app/views/fields/_field.html.erb
<%# locals: (field:, order: Ordering::Order.new) %>
<%# Table header for a field. Used in layers/rows and broadcast from FieldsController and from Field hooks. %>

<%# If there are several layers, there are several “new field” buttons.
   We need to identify the element when broadcasting a new field before this one in Field#after_create_commit %>
<% element_id = field.persisted? ? dom_id(field) : dom_id(field.layer, :new_field) %>

<th id="<%= element_id %>" class="dropdown layer-table__th layer-table__th--field" data-controller="dropdown">
  <div class="<%= class_names("layer-table-th__contents", "layer-table-th__contents--resizable" => field.persisted?) %>"
       data-dropdown-target="trigger"
       data-action="click->dropdown#toggle"
       aria-haspopup="true">
    <% if field.persisted? %>
      <%= embedded_svg "lock-closed.svg", class: "icon--smaller" if field.locked? %>
      <%= embedded_svg "triangle.svg", class: "icon--smaller field-form__icon--ascending" if order.field == field && order.asc? %>
      <%= embedded_svg "triangle.svg", class: "icon--smaller" if order.field == field && order.desc? %>
      <%= field.label %>
      <%= embedded_svg "chevron_droite.svg", class: "icon--smaller icon--tinted dropdown__indicator" %>
    <% else %>
      <button class="icon-button icon-button--small" title="<%= t("helpers.link.field.new") %>">
        <%= embedded_svg "ajouter_cercle.svg", class: "icon--small icon--tinted" %>
      </button>
    <% end %>
  </div>
  <div class="dropdown__content" role="menu" data-dropdown-target="content">
    <%# frame_id is the same as in fields/form.html.erb %>
    <% frame_id = field.persisted? ? dom_id(field, :frame) : dom_id(field.layer, :new_field_frame) %>
    <% if field.persisted? %>
      <%= turbo_frame_tag frame_id, src: edit_field_path(field, order_direction: order.direction_for_field(field)), loading: "lazy" %>
    <% else %>
      <%= turbo_frame_tag frame_id, src: new_layer_field_path(field.layer), loading: "lazy" %>
    <% end %>
  </div>
</th>

app/views/fields/form.html.erb
<%# params: @field, @order_direction %>
<%# Form for a field; used in fields#new and fields#edit %>

<%# In addition to FieldPolicy, most attributes are disabled if the field is locked. %>
<% update_disabled = !policy(@field).update? || @field.locked? %>

<%# frame_id is the same as in fields/_field.html.erb %>
<% frame_id = @field.persisted? ? dom_id(@field, :frame) : dom_id(@field.layer, :new_field_frame) %>
<%= turbo_frame_tag frame_id do %>
  <%# If there are several layers, there are several “new field” form.
      We need to use a namespace in the form so that radio buttons and checkbox labels identify the items in the right form. %>
  <% form_namespace = @field.persisted? ? dom_id(@field) : dom_id(@field.layer, :new_field) %>
  <%= form_with model: @field.new_record? ? [@field.layer, @field] : @field, namespace: form_namespace, class: "form" do |form| %>
    <div class="card__main-content form">
      <% if @field.new_record? %>
        <h3 class="form__header"><%= t("helpers.link.field.new") %></h3>
      <% end %>
      <%= form.hidden_field :layer_id %>
      <div class="form__field">
        <%= form.text_field :label, disabled: update_disabled %>
      </div>

      <div class="form__field">
        <%= form.collection_radio_buttons(:field_type, Field.field_types.keys,
              :to_s, -> { Field.human_attribute_name("field_types.#{_1}") },
              include_hidden: false) do |radio| %>
          <%# show the radio only if the field is new, or if this radio is the field type %>
          <%# field type can only be set initially %>
          <% if @field.new_record? || @field.field_type == radio.object %>
            <div class="form__field">
              <%= radio.label class: "field-form__label" do %>
                <%= radio.radio_button class: "field-form__type-radio", required: @field.new_record?, disabled: @field.persisted? %>
                <%= radio.label %>
              <% end %>
              <% if radio.object == "text" %>
                <div class="field-form__type-param form__field form__field--inline">
                  <%= form.check_box :text_is_long, disabled: update_disabled %>
                  <%= form.label :text_is_long %>
                </div>
              <% elsif radio.object == "enum" %>
                <div class="field-form__type-param form__field" data-controller="enum-values">
                  <template data-enum-values-target="template">
                    <%= form.text_field :enum_values, value: nil, multiple: true, disabled: update_disabled, placeholder: t("helpers.placeholder.field.enum_value"), data: {enum_values_target: "value", action: "input->enum-values#valueInput"} %>
                  </template>
                  <% @field.enum_values&.each do |val| %>
                    <%= form.text_field :enum_values, value: val, multiple: true, disabled: update_disabled, placeholder: t("helpers.placeholder.field.enum_value"), data: {enum_values_target: "value", action: "input->enum-values#valueInput"} %>
                  <% end %>
                </div>
              <% elsif radio.object == "territory" %>
                <div class="field-form__type-param form__field">
                  <%= form.collection_check_boxes(:territory_category_ids, TerritoryCategory.all,
                        :id, :to_s,
                        include_hidden: false) do |check| %>
                    <%= check.label do %>
                      <%= check.check_box(disabled: @field.persisted?) %>
                      <%= check.text %>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>

      <% if @field.persisted? %>
        <div class="form__section">
          <div class="form__field">
            <div class="form__field form__field--inline">
              <%= form.check_box :locked, disabled: !policy(@field).update? %>
              <%= form.label :locked %>
            </div>
            <div class="form__field form__field--inline">
              <%= form.check_box :display_in_tooltip, disabled: !policy(@field).update? %>
              <%= form.label :display_in_tooltip %>
            </div>
          </div>
        </div>

        <div class="form__field field-form__order">
          <%= t(".order_by") %>
          <div class="field-form__order-direction">
            <% if @order_direction == "ASC" %>
              <%= link_to t(".order_asc"), @field.layer, class: "field-form__current-order", data: {turbo_frame: dom_id(@field.layer)} %>
            <% else %>
              <%= link_to t(".order_asc"), layer_path(@field.layer, order_by: {@field.id => "ASC"}), data: {turbo_frame: dom_id(@field.layer)} %>
            <% end %>
            <% if @order_direction == "DESC" %>
              <%= link_to t(".order_desc"), @field.layer, class: "field-form__current-order", data: {turbo_frame: dom_id(@field.layer)} %>
            <% else %>
              <%= link_to t(".order_desc"), layer_path(@field.layer, order_by: {@field.id => "DESC"}), data: {turbo_frame: dom_id(@field.layer)} %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="card__footer-content">
      <%= submit_tag t("helpers.submit.field.update"), class: "button button--confirm", disabled: !policy(@field).update? %>
      <% if @field.persisted? %>
        <%= link_to @field, data: {turbo_method: :delete}, class: "button button--delete button--lowercase",
              disabled: update_disabled do %>
          <%= t("helpers.link.field.delete") %>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>